name: Scrape ClubSpeed leaderboard

on:
  # Manual trigger from the Actions tab
  workflow_dispatch:
  # Weekly schedule: Mondays 09:00 UTC
  schedule:
    - cron: '0 9 * * 1'

permissions:
  contents: write  # needed for committing updated data files

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- Best-lap leaderboard (site uses data/leaderboard.json) ---
      - name: Run leaderboard scraper (best laps)
        env:
          CUST_ID: ${{ secrets.CUST_ID }}             # REQUIRED: your encoded CustID (e.g., MTExNDczMQ==)
          START_YEAR: "2025"                          # only include heats from 2025+
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }} # optional; defaults to PGP Kent if unset
          FILTER_DRIVERS: "0"                         # leave 0; UI filters via drivers.csv
        run: |
          python scraper/scrape.py

      # --- Per-driver full lap export (writes data/all_laps.csv) ---
      # Set DEBUG=1 to also dump HTML into data/debug_html/*.html and commit them
      - name: Run ALL-LAPS scraper (per driver)
        env:
          START_YEAR: "2025"
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
          DEBUG: "1"
          DEBUG_MAX_DUMPS: "6"
          DEBUG_DUMP_VARIANTS: "default,print"
        run: |
          python scraper/scrape_all_laps.py

      # Diagnostic: show CSV status and git changes
      - name: Verify all_laps.csv changed
        run: |
          echo "== ls -l data =="
          ls -l data || true
          echo "== head/tail of all_laps.csv =="
          if [ -f data/all_laps.csv ]; then
            wc -l data/all_laps.csv
            head -n 5 data/all_laps.csv || true
            tail -n 5 data/all_laps.csv || true
          else
            echo "data/all_laps.csv not found"
          fi
          echo "== git status =="
          git status --porcelain
          echo "== git diff names =="
          git diff --name-only || true

      # Commit updated data
      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update leaderboard, all_laps, and debug HTML"
          file_pattern: |
            data/leaderboard.json
            data/all_laps.csv
            data/debug_html/*.html
          add_options: '-A'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'

      # Show commit details
      - name: Show last commit details
        run: |
          echo "== last commit =="
          git log -1 --name-status
