name: Scrape PGP Heats

on:
  workflow_dispatch: {}
  schedule:
    - cron: "18 10 * * *"  # daily 10:18 UTC; adjust cadence as you wish

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (continue from last_heat or 75533)
        run: |
          python -m scraper.run

      - name: Commit & push data updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "data: update heats + driver index"
            git push
          fi

