name: Scrape ClubSpeed leaderboard

on:
  workflow_dispatch:   # lets you trigger manually
  schedule:
    - cron: '0 9 * * 1'   # every Monday at 09:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow committing changes
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          CUST_ID: ${{ secrets.CUST_ID }}
          YEARS: ${{ secrets.YEARS }}
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
        run: |
          python scraper/scrape.py

      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update leaderboard.json"
          file_pattern: data/leaderboard.json
          
      - name: Run ALL-LAPS scraper
        env:
          START_YEAR: "2025"
          SITE_BASE_URL: ${{ secrets.SITE_BASE_URL }}
        run: |
          python scraper/scrape_all_laps.py

      - name: Commit all_laps.csv
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update all_laps.csv"
          file_pattern: data/all_laps.csv
