name: Scrape PGP Heats

on:
  schedule:
    # every 15 minutes (UTC)
    - cron: "*/7 * * * *"
  workflow_dispatch:
    inputs:
      max_heats:
        description: "Max heats to scrape this run"
        required: false
        default: "200"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper (max 200 heats)
        shell: bash
        run: |
          MAX="${{ github.event.inputs.max_heats }}"
          MAX="${MAX:-200}"
          echo "Running scraper with max=$MAX"
          python -m scraper.run --max "$MAX"

      - name: Commit & push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No new data to commit."
          else
            git commit -m "Update scraped heats"
            git push
          fi
